language: node_js
node_js:
    - "10"

before_install:
  - npm install -g grunt-cli

install:
    - npm install

cache:
  directories:
    - node_modules

script:
  - npm run generate
  - npm run generate-api-docs
