version: 0.2

env:
  variables:
    BUILD_ID: "`cat /proc/sys/kernel/random/uuid`"

phases:
  install:
    commands:
      - echo Entered the install phase...
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update
      - apt-get install -y openjdk-8-jdk
      - npm update -g npm
      - npm install -g grunt-cli

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run generate
      - npm run generate-api-docs

  post_build:
    commands:
      - echo Entered the post_build phase with BUILD_ID as $BUILD_ID...
      - aws s3 sync --delete dist "s3://www.starpeace-project.com/$BUILD_ID"
      - aws cloudfront update-distribution --id E1IMGZSYYR5EOR --generate-cli-skeleton
      - echo Build completed on `date`

artifacts:
  files:
    - dist/**/*
